Update RiceInstaller

diff --git a/RiceInstaller b/RiceInstaller
--- a/RiceInstaller
+++ b/RiceInstaller
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 #	Script to install my dotfiles
-#   Author: Deyusha69
+#   Author: z0mbi3
 #	url: https://github.com/Deyusha69
 
 CRE=$(tput setaf 1)
@@ -31,8 +31,8 @@ logo () {
 	       &&&         &&&
 	       &&&////   &&
 	          &&//@@@**
-	            ..***               
-			  deyusha69 Script\n\n"
+	            ..***                
+			  z0mbi3 Script\n\n"
     printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
     sleep 2
 }
@@ -40,7 +40,7 @@ logo () {
 	
 logo "Welcome!"
 printf '%sThis script will install needed dependencies and copy my dotfiles to your hyprland setup.%s\n\nThis installer script does NOT change any configuration of your system.\nIts just a script that copies and moves my dotfiles to your ~/.config directory\n\n' "${CRE}" "${CNC}"
-sleep 3
+sleep 5
 
 while true; do
 	read -rp " Do you wish to continue? [y/N]: " yn
@@ -51,75 +51,97 @@ while true; do
 		esac
     done
 			clear
+			
+logo "Installing needed packages.."
+
+dependencias=(base-devel dunst git geany ranger papirus-icon-theme zsh wofi thunar thunar-archive-plugin polkit-gnome swayidle blueman brightnessctl eog pavucontrol playerctl grim slurp pipewire wireplumber wf-recorder file-roller kitty starship viewnior wl-clipboard networkmanager noise-suppression-for-voice swaybg ttf-droid noto-fonts-emoji)
+
+is_installed() {
+  pacman -Qi $1 &> /dev/null
+  return $?
+}
+
+printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
+for paquete in "${dependencias[@]}"
+do
+  if ! is_installed $paquete; then
+    sudo pacman -S $paquete --noconfirm
+    printf "\n"
+  else
+    printf '%s%s is already installed on your system!%s\n' "${CGR}" "$paquete" "${CNC}"
+    sleep 1
+  fi
+done
+sleep 2
+clear
 
 logo "Checking if yay is installed"
 
-	if pacman -Qi yay >/dev/null 2>&1; then
-		printf "Yay is installed\n\n"
+	if ! command -v yay &>/dev/null; then
+		printf "%s%sError YAY is not installed%s\n" "${BLD}" "${CRE}" "${CNC}"
+		sleep 1
+		printf "%s%sInstalling YAY..%s\n\n" "${BLD}" "${CYE}" "${CNC}"
+		sleep 1
+		git clone https://aur.archlinux.org/yay-bin && cd yay-bin && makepkg -si && cd && rm -rf yay-bin
 	else
-		printf "installing yay..\n\n"
-		sudo pacman -Syu git && git clone https://aur.archlinux.org/yay-bin && cd yay-bin && makepkg -si && cd
+		printf "%s%sYAY is already installed on your system%s\n" "${BLD}" "${CGR}" "${CNC}"
 	fi
 sleep 2
 clear
-		
-logo "Installing needed packages.."
 
-	yay -S --noconfirm --needed hyprland-bin waybar-hyprland wlogout wofi dunst papirus-icon-theme catppuccin-gtk-theme-mocha thunar thunar-archive-plugin polkit-gnome wlsunset swayidle udev-block-notify blueman brightnessctl swaylock-effects xdg-desktop-portal-hyprland-git
-				
-			
-	yay -S --noconfirm --needed firefox wdisplays eog pavucontrol playerctl grim slurp pipewire wireplumber wf-recorder file-roller kitty zsh starship viewnior wl-clipboard networkmanager nwg-look-bin inotify-tools-git fnm sddm-git noise-suppression-for-voice swaybg geany ttf-droid noto-fonts-emoji
-				
-				
-				
-				
-					 
-			  
-clear
-			 
+
+
 logo "Cloning Rice!"
+[ -e ~/dotfiles ] && rm -rf ~/dotfiles
 printf "Cloning rice from https://github.com/Deyusha69/dotfiles\n\n"
 git clone --depth=1 https://github.com/Deyusha69/dotfiles.git
 sleep 2
 clear
 
+
 logo "Copying Rice.."
-printf "Copying files to respective directories..\n\n"
+printf "Copying files to respective directories..\n"
 
-if [ -d "$HOME/.config" ]; then
-	cp -r ~/dotfiles/.config/* ~/.config
+if [ ! -d $HOME/.config ]; then
+	mkdir -p $HOME/.config
+	cp -r $HOME/dotfiles/.config/* $HOME/.config
 else
-	mkdir -p ~/.config && cp -r ~/dotfiles/.config/* ~/.config
+	cp -r $HOME/dotfiles/.config/* $HOME/.config
 fi
 
-if [ -d "$HOME/.icons" ]; then
-	cp -r ~/dotfiles/.icons/* ~/.icons
+if [ ! -d $HOME/.local/bin ]; then
+	mkdir -p $HOME/.local/bin
+	cp -r $HOME/dotfiles/.local/bin/* $HOME/.local/bin
 else
-	mkdir -p ~/.icons && cp -r ~/dotfiles/.icons/* ~/.icons
+	cp -r $HOME/dotfiles/.local/bin/* $HOME/.local/bin
 fi
 
-if [ -d "$HOME/.local/bin" ]; then
-	cp -r ~/dotfiles/.local/bin/* ~/.local/bin
+if [ ! -d $HOME/.local/share/applications ]; then
+	mkdir -p $HOME/.local/share/applications
+	cp -r $HOME/dotfiles/.local/applications/* $HOME/.local/share/applications
 else
-	mkdir -p ~/.local/bin && cp -r ~/dotfiles/.local/bin/* ~/.local/bin
+	cp -r $HOME/dotfiles/.local/applications/* $HOME/.local/share/applications
 fi
 
-if [ -d "$HOME/.local/share" ]; then
-	cp -r ~/dotfiles/.local/share/* ~/.local/share
+if [ ! -d $HOME/.local/share/fonts ]; then
+	mkdir -p $HOME/.local/share/fonts
+	cp -r $HOME/dotfiles/.local/fonts/* $HOME/.local/share/fonts
 else
-	mkdir -p ~/.local/share && cp -r ~/dotfiles/.local/share/* ~/.local/share
+	cp -r $HOME/dotfiles/.local/fonts/* $HOME/.local/share/fonts
 fi
 
-cp -r $HOME/dotfiles/misc/firefox/chrome $HOME/.mozilla/firefox/*.default-release/
-cp -r $HOME/dotfiles/misc/firefox/user.js $HOME/.mozilla/firefox/*.default-release/
+cp -r $HOME/dotfiles/home/.gtkrc-2.0 $HOME
+cp -r $HOME/dotfiles/home/.lessfilter $HOME
+cp -r $HOME/dotfiles/home/.profile $HOME
+cp -r $HOME/dotfiles/home/.zshenv $HOME
 
-cp -r ~/dotfiles/.gtkrc-2.0 ~
-cp -r ~/dotfiles/.lessfilter ~
-cp -r ~/dotfiles/.profile ~
-cp -r ~/dotfiles/.zshenv ~
-
-printf "\n\nFiles copied succesfully\n\n"
+printf "%s%sFiles copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 sleep 2
+clear
+
+logo "Installing needed packages from AUR"				 
+yay -S hyprland-bin waybar-hyprland wlogout catppuccin-gtk-theme-mocha wlsunset udev-block-notify blueman swaylock-effects xdg-desktop-portal-hyprland-git firefox wdisplays nwg-look-bin inotify-tools-git fnm sddm-git --removemake --cleanafter
+sleep 2	  
 clear
 
 logo "Reloading fonts.."
@@ -128,9 +150,14 @@ printf "%s%sFonts reloaded succesfully!%s\n" "${BLD}" "${CGR}" "${CNC}"
 sleep 2
 clear
 
-chmod -R +x ~/.config/hypr/scripts/
-
-logo "Installation finished"
-printf "%sNow logout your session, select hyprland and log in.%s \n\n" "${CRE}" "${CNC}"
+logo "Enabling zsh"
 chsh -s /usr/bin/zsh
 zsh
+printf "%s%sDone!!%s\n" "${BLD}" "${CGR}" "${CNC}"
+sleep 2
+clear
+
+logo "Installation finished"
+sudo systemctl enable sddm
+sudo systemctl start sddm
+printf "%s%sSelect hyprland and log in.%s\n\n" "${BLD}" "${CRE}" "${CNC}"
